version: "3.8"
services:
  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: redlight
      POSTGRES_USER: user123
      POSTGRES_PASSWORD: password
      TZ: Asia/Seoul
    volumes:
      - ./db/postgres/data:/var/lib/postgresql/data
      - ./db/postgres/init:/docker-entrypoint-initdb.d
    command:
      - "postgres"
      - "-c"
      - "max_connections=100"
      - "-c"
      - "client_encoding=UTF8"
    networks:
      - app-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.1
    container_name: elasticsearch
    environment:
      - node.name=es-node
      - cluster.name=es-cluster
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - app-network

volumes:
  esdata:

networks:
  app-network:
    driver: bridge
