version: "3.8"
services:
  updater:
    build: .
    container_name: sp500-updater
    env_file:
      - .env
    networks:
      - redlight_default
    environment:
      DB_HOST: redlight
networks:
  redlight_default:
    external: true
